Unwrap dropbits option
usnistgov/dastard pull request #274
Opened 2022-05-26 18:53 UTC by ggggggggg

2022-05-26 18:53 UTC, closed without merging

2022-05-26 19:00 UTC, ggggggggg commented
The tests failed, but I don't think it's real. It's just a segfault in the `Abaco` tests, which is why I always skip the abaco tests! But this change is about abaco, so doesn't seem good to skip.  
![image](https://user-images.githubusercontent.com/5192577/170558086-e73b7f9a-1c36-4667-9327-535391876f9e.png)

2022-05-26 22:08 UTC, ggggggggg commented
So there is a real failure in the `packet_test.go`, probably because I changed how timestamps without units from tlvs are interpreted. I can't understand the intention of how they were supposed to behave, so my inclination is to just change the tests to pass.

```
--- FAIL: TestTLVs (0.00s)
    packets_test.go:241: PacketTimestamp = {217304205466533888 1e+09}, want {3315799033608 0}
```

Do you want to look at it before I do that and see if you have a different opinion on how I should deal with it?

2022-05-31 20:23 UTC, joefowler requested changes
This looks mostly good to me. You will see that I believe that the `DropBits` boolean is extraneous and should be removed. Let me explore that proposal and see if it works. I'll start from the PR and make sure that I can remove that field.

2022-05-31 20:23 UTC, joefowler commented on packets/packets.go
> +			// we assume a 64 bit int with units of nanoseconds
I guess I can approve this, but I'm a little concerned that we'll be making life more difficult in the future. The hope is that no timestamp source that has any meaningful units would use the `tlvTIMESTAMP` type but would always favor `tlvTIMESTAMPUNIT`. 

What was wrong with the previous choice to set `PacketTimestamp.Rate=0`? Did something break when we did that?

2022-05-31 20:23 UTC, joefowler commented on packets/packets.go
> +			// we assume a 64 bit int with units of nanoseconds
(I could totally imagine that Rate=0 breaks something.)

2022-05-31 20:23 UTC, joefowler commented on abaco.go
> +
If you remove the `DropBits` field like I propose (see other comments), then the parameters are more automatically self-consistent, and this entire test becomes unnecessary.

2022-05-31 20:23 UTC, joefowler commented on abaco.go
> +	AbacoUnwrapOptions
Ooh! Nice use of "composition" in Golang.

2022-05-31 21:02 UTC, joefowler approved these changes